<a href="https://colab.research.google.com/github/Aditi-2840/Dmdw-Lab-Assignments/blob/main/Dataset_importing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
url = 'https://raw.githubusercontent.com/GouriNayak/DMDW/main/Data.csv'

In [2]:
import pandas as pd

In [3]:
data =pd.read_csv(url)

In [4]:
data

age gender   income  spending
0   22       m   18000      6000
1   25       f   30000      8000
2   31       f   35000     12000
3   35       m   40000     18000

In [5]:
from google.colab import files

In [6]:
uploaded = files.upload()

In [7]:
data

age gender   income  spending
0   22       m   18000      6000
1   25       f   30000      8000
2   31       f   35000     12000
3   35       m   40000     18000

In [9]:
import io

In [ ]:
df1 = pd.read_csv(io.BytesIO(uploaded['Data.csv']))

In [ ]:
data

In [11]:
import numpy

In [13]:
arr=numpy.array([1,2,3,4,5])

In [14]:
arr

array([1, 2, 3, 4, 5])

In [15]:
import numpy as np

In [16]:
arr=np.array([1,2,3,4,5])

In [17]:
print(arr)

[1 2 3 4 5]


In [18]:
import numpy as np

In [19]:
print('np._version_')

np._version_


In [20]:
import numpy as np

In [21]:
arr=np.array([1,2,3,4,5])

In [22]:
print(arr)

[1 2 3 4 5]


In [23]:
print(type(arr))

<class 'numpy.ndarray'>
